name: Release_Pipeline_Windows
on:
  push:
    branches:
      - main
  schedule:
    - cron: "00 02 * * *" # Scheduled it to run at 02:00 UTC [08:00 IST]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute Behave tests - Windows
        if: matrix.os == 'windows-latest'
        run: |
          behave .\features\OrgangeHRMLogin.feature
      - name: Execute Behave tests - MacOS
        if: matrix.os == 'macos-latest'
        run: |
          behave ./features/OrgangeHRMLogin.feature
      # - name: Execute Behave tests - Ubuntu
      # if: matrix.os == 'ubuntu-latest'
      # run: |
      # behave ./features/OrgangeHRMLogin.feature 
      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: JUnitReports/TESTS-*.xml
